# usa_ap_dict.py
# Support file for ledmap.py - Mark Harris
#
# This file houses dictionaries of US Airports that report Metars that will be displayed
# when the USA map is displayed by ledmap.py. The dicts below include;
#    a user defined dict of 183 airports
#    a dict with 1700+ airports for lower 48 states
#    a dict with almost 3000 airports including lower 48, Hawaii and Alaska
#
# The name of the dictionary that ledmap.py is using is 'usa_ap_dict',
# So be sure to define this with the desired list in the variables in ledmap.py
# Look for;
#    Choose which group of airports to display when 'USA' is chosen
#    usa_ap_dict = ap_3000_dict # or ap_user_dict or ap_1700_dict

# This is a user defined dict currently with 183 airports
ap_user_dict = {'USA':\
                ['KSAT','KHOU','KOLS','KCRP','KBRO','KIAH','KELP','KODO','KABI','KTUS',\
                'KLFT','KMSY','KBTR','KFTW','KSHV','KLBB','KMOB','KPNS','KJAN','KAMA',\
                'KOKC','KLIT','KMEM','KRSW','KSPG','KTLH','KBHM','KTUL','KXNA','KJAX',\
                'KSAV','KHSV','KATL','KMIA','KSGF','KPBI','KMCO','KEYW','KBNA','KCHA',\
                'KTYS','KAVL','KGSP','KCAE','KCHS','KCLT','KMYR','KFAY','KGSO','KRDU',\
                'KEVV','KSDF','KLEX','KLWB','KLYH','KCMH','KCLE','KPIT','KBUF','KRIC',\
                'KORF','KDCA','KROC','KBWI','KABE','KPHL','KACY','KSYR','KEWR','KALB',\
                'KJFK','KBDL','KPVD','KBOS','KMHT','KBGR','KPWM','KBTV','KFVE','KCVG',\
                'KDAY','KIND','KFWA','KDTW','KSBN','KFNT','KGRR','KSTL','KSPI','KPIA',\
                'KORD','KMLI','KMKE','K83D','KMCI','KMSN','KGRB','KCID','KDSM','KCKC',\
                'KASX','KMSP','KJMS','KOMA','KMHE','KBIS','KLNK','KPIR','KICT','KRAP',\
                'KECS','KLAA','KCYS','KCPR','KDEN','KMOT','KCOS','KBIL','KHDN','KMTJ',\
                'K46U','KGPI','KMSO','KGGW','KHVR','KCOE','KGEG','KAFO','KLGU','KSLC',\
                'KPSC','KONO','KBOI','KBNO','KPDX','KWMC','KAST','KTMK','KOTH','KNUW',\
                'KSEA','KAAT','KCEC','KACV','KRNO','KSMF','KSFO','KMRY','KFAT','KFMN',\
                'KBCE','KPGA','KABQ','KFLG','KSJN','KPRC','KLAS','KIGM','KHII','KPHX',\
                'KONT','KLAX','KSBA','KNYL','KSAN','KTYL']
                }


# Dictionary of 1700+ airports in lower 48 states that report Metars
ap_1700_dict = {'USA':\
               ['PADK','PAKH','PAUT','PAFM','PAKP','PANC','PALH','PAMR','PAGN','PANI',\
                'PANT','PANV','PARC','PAAK','PATQ','PABA','PABE','PABT','PALV','PABV',\
                'PFKT','PAFR','PABL','PATW','PALU','PAEH','PACZ','PACE','PARL','PALR',\
                'PAVA','PAJC','PAEC','PACR','PFCL','PACD','PACV','PASC','PADE','PABI',\
                'PADL','PADU','PAEG','PASY','PAII','PAEI','PAEL','PFEL','PAED','PAEM',\
                'PAZK','PAFA','PAKF','PAFK','PAFB','PFYU','PAFN','PAGB','PAGA','PAGM',\
                'PAGL','PAGK','PAGS','PAHN','PAHZ','PAHV','PAHC','PAHO','PAOH','PAHP',\
                'PAHL','PAHS','PAHY','PAIG','PAIL','PAIM','PAJN','PAFE','PALG','PAKV',\
                'PAEN','PAKT','PAIK','PAVC','PAKN','PAKI','PAVL','PAKW','PADQ','PAJZ',\
                'PAOT','PAKK','PAKU','PFKW','PAML','PAMB','PADM','PAMX','PAMC','PAIN',\
                'PAMY','PAMM','PAMD','PAMH','PAMO','PABN','PANA','PAOU','PANN','PANW',\
                'PAFS','PAWN','PAOM','PFNO','PAOR','PAQT','PPNU','PALP','PPIT','POLI',\
                'PFNU','PAAQ','PAXK','PAPG','PAPN','PAPM','PAPO','PPIZ','PAAD','PATO',\
                'PAAP','PALJ','PAPC','PAPH','PAPR','PAUD','PAPT','PAQH','PADG','PARD',\
                'PARY','PARS','PASM','PASD','PASA','PACM','PASK','PASO','PAWD','PAHX',\
                'PFSH','PASH','PAGH','PASI','PAGY','PASW','PADT','PASL','PALK','PASX',\
                'PFWS','PASV','PAPB','PAMK','PAER','PASN','PAJV','PASP','PATK','PATA',\
                'PATL','PATE','PATC','PATG','PAOO','PAUM','PAUN','PABR','PAVD','PAVW',\
                'PAWI','PAIW','PAWS','PAWM','PAWR','PAKX','PAUO','PAIZ','PAWG','PAYA',\
                'PHBK','PHSF','PHHN','PHIK','PHTO','PHNL','PHOG','PHKO','PHJR','PHLU',\
                'PHNG','PHJH','PHNY','PHLI','PMDY','PHMO','PHMK','PHHI',\
                'CYXZ','CYLD','CYXR','CYQB','KCAR','KPQI','KHUL','KMLT','KPNN','KBGR','KBHB','KBST','KRKD','KBXM','KPWM','KSFM','KDAW','KPSM','KLWM','KBVY','KPVC','KHYA','KACK','KMVY','KPYM','KEWB','KOQU','KWST','KGON','KHTO','KFOK','KHWV','KISP','KFRG','KJFK','KBLM','KNEL','KACY','KWWD','KGED','KOXB','KSBY','KMFV','KNTU','KONX','KMQI','KECG','KEDE','KASJ','KIXA','KAVC','KW78','KBCB','KPSK','KBLF','KJFZ','KPBX','KSJS','KCPF','KJKL','KRGA','KDVK','KBRY','KEKX','KKY8','KEVV','KCUL','KOLY','KLWV','KRSV','KHUF','KPRG','KIKK','KGYY','KMDW','KMGC','KBEH','KLWA','KBIV','KMKG','KFFX','KLDM','KMBL','KFKS','KTVC','KACB','KCVX','KSJX','KISQ','KERY','KCIU','KANJ','CYSB','CYYB','CYOW','CYND','CYMX','CYUL','CYHU','CYRQ','CYSC','KWVL','KAUG','KLEW','KLCI','KCON','KMHT','KASH','KBED','KBOS','KOWD','KSFZ','KPVD','KIJD','KHFD','KOXC','KDXR','KLGA','KEWR','KCDW','KMMU','KTTN','KPNE','KPHL','KMIV','KDOV','K33N','KESN','KCGE','KNHK','KNUI','KXSA','KFYJ','KPHF','KORF','KPVG','KFKN','KAKQ','KEMV','KBKT','KFVX','KLYH','KROA','KBKW','KIOB','K27K','KLEX','KFFT','KSDF','KJVY','KHNB','KFRH','KDCY','KBMG','KGPC','KCFJ','KFKR','KLAF','KMCX','KRZL','KOXI','KVPZ','KPPO','KSBN','KEKM','KGRR','KRQB','KCAD','KGLR','KMGN','KPLN','KSLH','CYZE','CYVV','CYQA','KOGS','KMSS','KEFK','KBML','KHIE','KMPV','KRUT','KVSF','KEEN','KORE','KORH','KCEF','KBAF','KBDL','KPOU','KMGJ','KMSV','KMPO','KABE','KCKZ','KRDG','KLNS','KMQS','KILG','KAPG','KMTN','KBWI','KADW','KDAA','KNYG','KRMN','KLKU','KOFP','KRIC','KPTB','KHSP','KLWB','KCRW','KHTS','KDWU','KFGX','KIMS','KBAK','KGEZ','KHFY','KIND','KOKK','KGUS','KGGP','KRCR','KASW','KGSH','KIRS','KAZO','KBTL','KY70','KAMN','KMOP','KOSC','KAPN','KPZQ','CYKF','CYYZ','CYOO','CYPQ','CYTR','CYGK','KART','KGTB','KSLK','KPBG','KBTV','KGFL','KAQW','KPSF','KALB','KSCH','KNY0','KRME','KVGC','KOIC','KBGM','KAVP','KHZL','KIPT','KSEG','KCXY','KTHV','KDMW','KHGR','KFDK','KGAI','KJYO','KIAD','KHEF','KCJR','KCHO','KSHD','KPMH','KLUK','KCVG','KHLB','KMQJ','KUMP','KMIE','KMZZ','KHHG','KFWA','KOEB','KJYM','KTEW','KLAN','KRNP','KMBS','KHYX','KCFS','KBAX','CYXU','CYHM','CYSN','KIAG','KBUF','KROC','KFZY','KSYR','KIUA','KPEO','KELM','KELZ','KOLE','KDKK','KJHW','KBFD','KOYM','KDUJ','KFIG','KUNV','KAOO','KHMZ','KCBE','KOKV','KW99','KEKN','KW22','KPKB','KUNI','KRZT','KI23','KMWO','KHAO','KOXD','KRID','KVES','KVNW','KDFI','KADG','KOZW','KPTK','KPHN','CYZR','CYCK','KERI','KHZY','KGKJ','KFKL','KIDI','KJST','KLBE','K2G4','KMGW','KCKB','KCDI','KZZV','KLHQ','KLCK','KTZR','KUYF','KSGH','KI19','KDAY','KEDJ','KAXV','KAOH','KOWX','KFDY','KTDZ','KTOL','KDUH','KTTF','KONZ','KDTW','CYQG','KDET','KMTC','KCGF','KYNG','KBTP','KAGC','KAFJ','KHLG','KVTA','KCMH','KOSU','KMRT','KDLZ','K4I3','KMNN','KMFD','KBJJ','KPIT','KBVI','KCAK','KAKR','KCLE','KLPR','KPCW','MYGF','MYEM','MYNN','MYAF','KMTH','KEYW','KCYD','KDSF','KVOA','KMIS','KLNQ','KHSA','KHBG','KPIB','KLUL','KMEI','KNMM','KNJW','KSTF','KGTR','KCBM','KM40','KTUP','KCRX','KSZY','KSNH','KRVE','KHZD','KPHT','KCEY','KM25','K5M9','KTWT','KM21','KBWG','KCLW','KSME','KLOZ','KLNP','KVJI','KMWK','KSIF','KTDF','KHNZ','KLHZ','KPGV','KOCW','K7W6','KHSE','KMRH','KNCA','KILM','KSUT','KCRE','KMYR','KHYW','KGGE','KCHS','KJZI','KNBC','KHXD','KSAV','KSVN','KLHW','KBQK','KSSI','KFHB','KJAX','KCRG','KNIP','KSGJ','KFIN','KOMN','KDAB','KEVB','KTTS','KTIX','KXMR','KCOF','KMLB','KX26','KVRB','KFPR','KSUA','KPBI','KBCT','KFXE','KOPF','KMIA','KTMB','KHST','KMKY','KAPF','KRSW','KPGD','KVNC','KSRQ','KPIE','KCGC','KCTY','K40J','KTLH','KAAF','KPAM','KECP','KDTS','KHRT','KPNS','KNPA','KJKA','KBFM','KMOB','KPQL','KBIX','KGPT','KDYA','KTCL','KJFX','K1M4','KMSL','K2M2','KMRC','KM02','KHOP','K1M5','K8A3','KSCX','KJAU','KMOR','K0VG','KGCY','KTRI','K0A9','K6A4','KGEV','KUKF','KINT','KGSO','KBUY','KRDU','KJNX','KGWW','KISO','KEWN','KNKT','KOAJ','KDPL','KCTZ','KEYF','KCPC','KMAO','KFLO','KCKI','KMKS','KDYB','KRBW','KAQX','KJYL','KTBR','KCWV','KRVJ','KJES','KAYS','KVQQ','K28J','KSFB','KORL','KMCO','KISM','KAGR','KSEF','KOBE','KX07','KGIF','KLAL','KTPA','KZPH','KBKV','KLEE','KINF','KOCF','KX60','KGNV','K42J','KLCQ','K24J','KVLD','KTVI','KBGE','K17J','KMAI','KBCR','K54J','KCEW','KNSE','KGZH','KSEM','KMGM','K1A9','KEET','KEKY','KBHM','KCMD','KDCU','KGZS','KLUG','KJWN','KXNX','KM54','KSRB','KCSV','KRKW','KTYS','GKT','KMRN','KHKY','KSVH','KRUQ','KEXX','KHBI','KSCR','KTTA','KHRJ','KFAY','KPOB','KSOP','KHFF','KMEB','KRCZ','KCQW','KBBP','KUDG','KHVS','KCDN','KSMS','KMMT','KCUB','KXNO','KOGB','KBNL','KAIK','KDNL','K2J5','KMHP','KVDI','KAZE','KBHC','KAMG','KDQH','KHOE','KVAD','KMGR','KCXU','KBIJ','KDHN','KOZR','KEDN','K79J','KTOI','KAUO','KSCD','KPLR','KANB','KGAD','K8A0','KHUA','KMDQ','KFYM','KSYI','KMQY','KRNC','K2A0','KMMI','KRHP','K1A5','KAVL','KFQD','KIPJ','KJQF','KVUJ','KAFP','KEQY','KCLT','KUZA','KLKR','KDCM','KFDW','KEOE','KGRD','KHQU','KOKZ','K2J3','KSBO','KDBN','K48A','KEZM','KMQW','KTMA','KABY','KEUF','KLSF','KCSG','KPIM','KLGC','KCCO','KCTJ','KPUJ','KVPC','KRMG','K4A9','K4A6','KBGF','KTHA','KCHA','KRZR','KDZJ','KAJR','KTOC','KCEU','KLQK','KGMU','KSPA','KLUX','KAND','K18A','KIIY','K3J7','KMLJ','KWRB','KPXE','KCKF','KACJ','K6A1','KOPN','KFFC','KHMP','KATL','KPDK','KRYY','KCZL','KDNN','KJZP','KGVL','KJCA','KAHN','KCVC','KD73','KWDR','KLZU','KPZZ','KXER','KGHB','KAGI','KGUL','KHHV','KGYF','KPIL','KHRL','KTXW','KMFE','KEBG','KAPY','MMMV','MMCU','KT89','KPRS','KE38','KVHN','KPEQ','KINK','KCNM','KATS','KROW','KSXU','KLVS','KAXX','KRTN','KTAD','K4V1','KPUB','KLHX','KLAA','K3K3','KGCK','KGBD','KLYO','KHUT','KEWK','KEMP','KUKL','KOZS','KVIH','KFAM','KPCD','KMDH','KMWA','KM30','KPAH','KSIK','KDXE','KMAW','KTKX','KHKA','KDYR','KMKL','KM08','KFYE','KDLV','KUOX','K5A6','KMBO','KHKS','KJAN','K1R7','KMCB','KHDC','KASD','KNEW','KNBG','KGAO','KHUM','KARA','KLFT','K3R7','KCWF','KUXL','KORG','KBPT','KBMT','KGLS','KLBX','KBYY','KPSX','KPKV','KRKP','KTFP','KNGP','KCRP','KNQI','KIKG','KALI','KHBV','KLRD','MMNL','MMPG','K5T9','KT70','KDLF','KDRT','KOZA','KE41','KMDD','KMAF','KODO','KHOB','KCVS','KCVN','KTCC','KCAO','KJHN','KULS','K19S','KDDC','KPTT','KICT','KIAB','K1K1','KEQA','KK88','KLBO','KTBN','KPOF','K4M9','KARG','KJBR','KNQA','KAWM','KMEM','KUTA','KPMU','KCKM','KGWO','KJVW','KTVR','KVKS','KHEZ','KMSY','KAPS','KREG','KBTR','KHZR','KOPL','KACP','KPOE','KDRI','KJAS','K6R3','KOXO','KDWH','KIAH','KT41','KHOU','KLVJ','KAXH','KSGR','KARM','KVCT','KBEA','KCOT','KUVA','KSOA','KSJT','KBPG','KLUV','KGNC','KLBB','KPVW','KHRX','KDHT','KEHA','KHQG','KLBL','K3K8','KEGT','KWLD','KIDP','KPPF','KCNU','KSGF','KUNO','KBVX','KM19','KSGT','KPBF','KLLQ','KGLH','KMLU','KESF','KAEX','KLFK','KUTS','K11R','KELA','KPEZ','KCVB','KHDO','KJCT','KSWW','KSNK','KCDS','KAMA','KDUX','KGUY','KPYX','KGAG','KWWR','KAVK','KPNC','KBVO','KMIO','KHFJ','KPWB','KBBG','KHRO','KFLP','KBPK','KCCA','KSRC','KLRF','KLIT','KSUZ','KHOT','KADF','KCDH','KELD','KRSN','KIER','K3F3','KF17','KOCH','KDKR','KCFD','KCLL','KGYB','K3T5','KSEQ','KRND','KSSF','KSAT','K5C1','KERV','KT82','KDZB','KAQO','K81R','KBWD','KCOM','KABI','KDYS','KF05','KAXS','KPPA','KBGD','KE42','KHHF','KWDG','KSWO','KOWP','KTUL','KGCM','KGMJ','KROG','KASG','KFYV','KRUE','KCXW','K7M3','KMEZ','KDEQ','KTXK','KMNE','KBAD','KSHV','K4F2','KJSO','KPSN','KLXY','KLHB','KBAZ','KHYI','KAUS','KEDC','KT74','KGTU','KTPL','KILE','KGRK','KLZZ','KMNZ','KMKN','KGZN','KBTN','KBKD','KRPH','KCWC','KSPS','KFDR','KHBR','KCSM','KELK','KCLK','KOJA','KJWG','KCUH','KRVS','KH71','KXNA','KSLG','KTQH','KJSV','KFSM','KRKR','KHHW','KPRX','KOSA','KASL','KGGG','KTYR','KCRS','KCNW','KACT','KPWG','KSEP','KMWL','KDUC','KLAW','KCHK','KRCE','KPWA','KOKC','KOUN','KTIK','KCQB','KOKM','KMKO','KGZL','KMLC','KDUA','KF00','KSLR','KGVT','KTRL','KHQZ','KJWY','KCPT','KNFW','KAFW','KDTO','KLUD','KGLE','K1F0','KADM','KPVJ','KSNL','KSRE','KADH','KGYI','KTKI','KADS','KDFW','KGKY','KRBD','KNSI','KSBA','KLPC','KVBG','KSMX','KSBP','KPRB','KNLC','KHJO','KVIS','KBCE','KTEX','KRCV','KALS','KLAM','KSAF','K0E0','KSRR','KHMN','KELP','MMCS','MMCU','MMCN','MMGM','MMHO','KNRS','KNZY','KNUC','KAVX','KNTD','KOXR','KBFL','KDLO','KPTV','KINS','KSGU','KAZC','KKNB','KPGA','KCEZ','KDRO','KPSO','KAEG','KABQ','KBRG','KONM','KTCS','KLRU','KDNA','KDMN','KFHU','KOLS','KDMA','KRYN','KAVQ','KMZJ','KP08','KA39','KGXF','KLGF','KNYL','MMML','KIPL','KSEE','KRNM','KNKX','KCRQ','KSNA','KLGB','KTOA','KLAX','KBUR','KPMD','KWJF','KTSP','KNID','KVGT','KLSV','KFMN','KGNT','KSVC','KSAD','KIWA','KCHD','KL08','KF70','KHMT','KRIV','KRAL','KONT','KPOC','KEDW','KMHV','KLAS','KHND','KBVU','KGCN','KRQE','KGUP','KSJN','KJTC','KFFZ','KPHX','KGYR','KBXK','KBLH','KTRM','KPSP','KSBD','KL35','KVCV','KDAG','KIFP','KIGM','KCMR','KFLG','KTYL','KSOW','KPAN','KSDL','KDVT','KLUP','KHII','KEED','KSEZ','KPRC','KM75','K00U','KSHR','KBYG','KCPR','KRWL','KSAA','K33V','K20V','KLXV','KAEJ','KANK','KGUC','KMTJ','KCDC','KBIH','KFAT','KMAE','KCVH','KSNS','KMRY','KWVI','KSJC','KHAF','KSFO','KOAK','KSTS','KUKI','KLLR','KFOT','KACV','KCEC','KOTH','KONP','KTMK','KAST','KHQM','KUIL','CYYJ','KBLI','CYXC','CYXH','KHVR','KLWT','KBIL','KU68','KGEY','KWRL','KHSG','KRIW','KLND','KDWX','KSBS','KEGE','KASE','KAJZ','KGJT','KCNY','KHVE','KU52','KMLF','KTPH','KMMH','KMER','KMOD','KTCY','KLVK','KCCR','KAPC','KRBL','KRDD','KSIY','KMFR','K3S8','KRBG','KEUG','KCVO','KSLE','KMMV','KHIO','KSPB','KKLS','KCLS','KOLM','KSHN','KCLM','KNUW','KBVS','KS52','KOMK','K65S','KGPI','KCTB','KGTF','KHWQ','K6SO','KPOY','KCOD','KDUB','KPNA','KRKS','KCAG','KHDN','KEEO','KRIL','KPUC','K41U','KDTA','KELY','KHTH','KO22','KSCK','KC83','KO88','KSUU','KDWA','KMYV','KOVE','KCIC','KO05','KLMT','KUAO','KTTD','KPDX','KGRF','KTIW','KSEA','KPWT','KPAE','KAWO','KSZT','KMSO','KHLN','KBZN','KLVM','KJAC','K46U','KBPI','KEMM','KFBR','KVEL','K4VO','KU69','KPVU','KDPG','K05U','KTMT','KNFL','KCXP','KMEV','KTVL','KMHR','KSAC','KSMF','KLHM','KBAB','KAAT','KLKV','KS21','KBDN','KRDM','KS39','KDLS','KYKM','KELN','KEAT','KEPH','KMWH','KSKA','KDEW','KSFF','KCOE','KBTM','KRVF','KEKS','KDIJ','KRXE','KIDA','KAFO','K1U7','KEVW','KHCR','KU42','KTVY','KENV','KEKO','KBAM','KLOL','KRNO','KTRK','KRTS','KBNO','KGCD','K9S9','KHRI','KRLD','KPSC','KPUW','KLWS','KGIC','KSMN','KDLN','KPIH','KLGU','KBMC','KOGD','KSLC','KWMC','KBKE','KLGD','KPDT','KALW','KJSY','KMYL','KLLJ','KSUN','KBYI','KTWF','KJER','KGNG','KMUO','KBOI','KEUL','KONO','CYWG','CYHD','CYQT','KCMX','KSAW','KIMT','KMNM','KSUE','KGRB','KMTW','KSBM','KETB','KMWC','KMKE','KRAC','KENW','KUGN','KPWK','KORD','KDPA','KARR','KC09','KPNT','KTIP','KCMI','KMTO','K1H2','KFOA','KMVN','KSAR','KRAW','KGLY','KLRY','KOWI','KSLN','KRSL','KHYS','KTQK','KFCS','KCOS','KFLY','KAFF','KGNB','KLAR','KDGW','KGCC','KMLS','KGGW','KOLF','KXWA','CYEN','K06D','KHCO','KROX','KRRT','KBDE','KINL','KELO','KCKC','KIWD','KLNL','KEGV','KARV','KRHI','KTKV','KRRL','KAIG','KAUW','KCWA','KSTE','KPCZ','KATW','KOSH','KFLD','KUNU','KRYV','KUES','KBUU','KJVL','KRFD','KDKB','KVYS','KC75','KBMI','KAAA','KDEC','KTAZ','K3LF','KSLO','KENL','KBLV','KCPS','KSTL','KSUS','KFYG','KJEF','KCOU','KVER','KDMO','KSZL','KRCM','KLXT','KIXD','KLWC','KTOP','KFOE','KMHK','KFRI','KHLC','KOEL','KCBK','KITR','KLIC','KAPA','KBKF','KCFO','KDEN','KBJC','KBDU','KLMO','KFNL','KCYS','KEAN','KGUR','KECS','KW43','KBHK','K20U','KGDV','KSDY','KS25','KD60','KMIB','KMOT','KDVL','KRDR','KGFK','KCKN','KTVF','KBJI','KGPZ','KHIB','KORB','KCQM','KEVM','KDLH','KASX','KRCX','KPBH','KMDZ','KMFI','KISW','KVOK','KDLL','KMSN','KC29','KEFT','KFEP','KSQI','KPIA','KSPI','KIJX','KPPQ','KMYJ','KMBY','KMHL','KGPH','KMKC','KMCI','KK82','KNRN','KOIN','KADT','KSYF','K2V5','K2V6','KAKO','KSTK','KFMM','K82V','KTOR','KCUT','KRAP','KRCA','KSPF','KBWW','KDIK','KHZE','KBIS','KJMS','KBAC','KFAR','KJKJ','KDTL','KPKD','KCOQ','KHYR','KRPD','KEAU','KBCK','KCMY','KC35','KLNR','KMRJ','KSFY','KCWI','KDVN','KMLI','KGBG','KMQB','KI63','KUIN','KHAF','KEZZ','KSTJ','KMYZ','KMCK','KIML','KHEQ','KSNY','KIBM','KBFF','KCDR','KIEN','KHEI','KGWR','KBWP','KFFM','KADC','KBRD','KAIT','KRZN','KUBE','KLUM','KONA','KLSE','KY51','KOVS','KPDC','KDBQ','KMXO','KMUT','KBRL','KFSW','KEOK','KIRK','KEVU','KBIE','KHSI','KEAR','KLXN','KLBF','KOGA','KAIA','KGRN','KMBG','KABR','KBTN','KAXN','KRYM','KJMR','KROS','KOEO','KRNH','KRGK','KRST','KFKA','KDEH','KOLZ','KIIB','KVTI','KCID','KIOW','KAWG','KFFL','KTVK','KICL','KSDA','KAFK','KLNK','KJYR','KAUH','KGRI','KBBW','KTIF','KVTN','KPIR','KATY','KMOX','KGHW','KSTC','KCBG','KANE','KMSP','KSGS','KLVN','KFBL','KOWA','KTOB','KAUM','KCCY','KALO','KOOA','KOTM','KCNC','KI75','KCSQ','KRDK','KPMV','KOFF','KAHQ','KOLU','KODX','KANW','KICR','KHON','KCNB','KBBB','KBDH','KLJF','KHCD','KFCM','KMKT','KAEL','KFXY','KMCW','KHPT','KIFA','KGGI','KPEA','KOXV','KAIO','KOMA','KBTA','KFET','KOFK','KONL','KMHE','KMDS','KBKX','KMML','KGDB','KRWF','KULM','KFRM','KFOD','KBNW','KAMW','KTNU','KIKV','KDSM','KPRO','KHNR','KTQE','KLCG','KYKN','KFSD','KPQN','KOTG','KEST','KCIN','KDNS','KSUX','KLYV','KSHL','KSPW','KCKP','KLRJ','KSXK']
               }


# Dictionary of 2948 US airports that report Metars for lower 48, Hawaii and Alaska
ap_3000_dict = {'USA':\
               ['PADK','PAKH','PAUT','PAFM','PAKP','PANC','PALH','PAMR','PAGN','PANI',\
                'PANT','PANV','PARC','PAAK','PATQ','PABA','PABE','PABT','PALV','PABV',\
                'PFKT','PAFR','PABL','PATW','PALU','PAEH','PACZ','PACE','PARL','PALR',\
                'PAVA','PAJC','PAEC','PACR','PFCL','PACD','PACV','PASC','PADE','PABI',\
                'PADL','PADU','PAEG','PASY','PAII','PAEI','PAEL','PFEL','PAED','PAEM',\
                'PAZK','PAFA','PAKF','PAFK','PAFB','PFYU','PAFN','PAGB','PAGA','PAGM',\
                'PAGL','PAGK','PAGS','PAHN','PAHZ','PAHV','PAHC','PAHO','PAOH','PAHP',\
                'PAHL','PAHS','PAHY','PAIG','PAIL','PAIM','PAJN','PAFE','PALG','PAKV',\
                'PAEN','PAKT','PAIK','PAVC','PAKN','PAKI','PAVL','PAKW','PADQ','PAJZ',\
                'PAOT','PAKK','PAKU','PFKW','PAML','PAMB','PADM','PAMX','PAMC','PAIN',\
                'PAMY','PAMM','PAMD','PAMH','PAMO','PABN','PANA','PAOU','PANN','PANW',\
                'PAFS','PAWN','PAOM','PFNO','PAOR','PAQT','PPNU','PALP','PPIT','POLI',\
                'PFNU','PAAQ','PAXK','PAPG','PAPN','PAPM','PAPO','PPIZ','PAAD','PATO',\
                'PAAP','PALJ','PAPC','PAPH','PAPR','PAUD','PAPT','PAQH','PADG','PARD',\
                'PARY','PARS','PASM','PASD','PASA','PACM','PASK','PASO','PAWD','PAHX',\
                'PFSH','PASH','PAGH','PASI','PAGY','PASW','PADT','PASL','PALK','PASX',\
                'PFWS','PASV','PAPB','PAMK','PAER','PASN','PAJV','PASP','PATK','PATA',\
                'PATL','PATE','PATC','PATG','PAOO','PAUM','PAUN','PABR','PAVD','PAVW',\
                'PAWI','PAIW','PAWS','PAWM','PAWR','PAKX','PAUO','PAIZ','PAWG','PAYA',\
                'KEET','K8A0','KALX','K79J','KANB','KAUO','KAUB','K1R8','KEKY','KBHM',\
                'K0A8','K9A4','K3A1','KCMD','KDCU','KDYA','KDHN','KEDN','KEUF','KGZH',\
                'KCQF','K0J4','K4A9','KHEY','KSXS','KGAD','KPRN','KJKA','K1M4','K0J6',\
                'KHSV','KMDQ','KJFX','KLOR','KA08','KMXF','KMOB','KBFM','KMGM','KMSL',\
                'KOZR','KPLR','KRAM','K1A9','KHUA','K4A6','KSEM','KSCD','KASN','KTOI',\
                'KTCL','KVOA','KADF','KBVX','KSUZ','KH00','KVBT','KXNA','KBYH','KHKA',\
                'KCDH','KCXW','KCCA','K4M9','KDEQ','KELD','KFYV','KFLP','KFSM','KHRO',\
                'KHOT','KJBR','KLRF','KLIT','KMEZ','KLLQ','KBPK','KMWT','KM19','KORK',\
                'KLZK','KPBF','KROG','KRUE','KSRC','KSLG','KASG','KSGT','KTXK','KARG',\
                'KAWM','KPHX','KTUS','KA39','KBXK','KIFP','KCGZ','KIWA','KCHD','KAZC',\
                'KP08','KDMA','KDUG','KFLG','KFHU','KGXF','KGEU','KLGF','KLUF','KGYR',\
                'KGCN','K40G','KIGM','KHII','KMZJ','KFFZ','KOLS','KPGA','KPAN','KDVT',\
                'KALK','KPRC','KSAD','KSDL','KSEZ','KSOW','KJTC','KSJN','KTYL','KAVQ',\
                'KRYN','KCMR','KRQE','KINW','KYUM','KNOZ','KNYL','KNGZ','KAAT','KAPV',\
                'KACV','KAUN','KAVX','KBFL','KBAB','KBUO','KBYS','KL35','KBIH','KBLH',\
                'KL08','KO57','KBAN','KBUR','KBNY','KC83','KCXL','KCMA','KCZZ','KNFG',\
                'KCRQ','KO59','KO05','KCIC','KNID','KCNO','KO22','KCCR','KAJO','KSNA',\
                'KCEC','KDAG','KDWA','KEDU','KDLO','KEDW','K9L2','KNJK','KEMT','KBLU',\
                'KEKA','KL18','KFOT','KFCH','KFAT','KFUL','KGOO','KHAF','KHJO','KO18',\
                'KHHR','KHWD','KHES','KHMT','KCVH','KHGT','KNRS','KIPL','KIYK','KJAQ',\
                'KWJF','KPOC','KWHP','KNLC','KLHM','KLLR','KLVK','KLPC','KLGB','KSLI',\
                'KCQT','KLAX','KMAE','KMMH','KMYV','KMHR','KMCC','KMER','KMCE','KNKX',\
                'KMOD','KNUQ','KMHV','KSIY','KMRY','KMHS','KMWS','KF70','KAPC','KEED',\
                'K3A6','KNZY','KDVO','KOAK','KL52','KOKB','KNXF','KONT','KOVE','KOXR',\
                'KGXA','KPMD','KPSP','KPAO','KPRB','KO69','KPVF','KNTD','KPTV','K87Q',\
                'KRNM','KRBL','KRDD','KREI','KO32','KO88','KRAL','KRIV','KSAC','KSMF',\
                'KSNS','KCPU','KSBD','KSQL','KNUC','KSDB','KSDM','KSAN','KMYF','KSEE',\
                'KSFO','KSJC','KRHV','KSBP','KE16','KNSI','KSBA','KSMX','KSMO','KSTS',\
                'KIZA','KO87','KTVL','KSCK','KSVE','KTSP','KTRM','KTOA','KTCY','KSUU',\
                'KO86','KTRK','KNXP','KUKI','KCCB','KVCB','KVBG','KXVW','KVNY','KVCV',\
                'KVIS','KWVI','KO54','KAKO','KALS','KASE','K7BM','K0CO','KBDU','KBJC',\
                'KBKF','KAEJ','KITR','K1V6','KCWN','KCOS','KCRV','KCEZ','KFLY','KCAG',\
                'KC99','KRCV','KAJZ','KCFO','KAPA','KDEN','KFTG','KDRO','KEGE','KABH',\
                'KEIK','KFLA','KFCS','KFMM','KFNL','KGNB','KGJT','KGXY','KGUC','KHDN',\
                'KHEQ','K1JW','K72C','K20V','KLHX','KLAA','KVTP','KLXV','K1LW','KLIC',\
                'KLMO','KEEO','K1MW','KMYP','KMTJ','KMNH','K3MW','K1NW','KAIB','K1OW',\
                'KPSO','KPUB','K4V0','KCCU','KRIL','K04V','KANK','KSHM','KSPD','KSBS',\
                'KSTK','KSTR','K5SM','KTEX','KTAD','KAFF','K33V','K4V1','KC07','K4BM',\
                'KCPW','K2V5','K2V6','KBDR','KSNC','KDXR','KGON','KHFD','KMMK','KHVN',\
                'KOXC','KIJD','KBDL','KDOV','K33N','KGED','KILG','KAAF','KBOW','KBCT',\
                'K1J0','KBKV','KXMR','KNZC','KCLW','K2IS','KCEW','KCTY','KCGC','KDAB',\
                'K54J','KDED','KDTS','KEGI','KVPS','KEGC','KFHB','KFIN','KFLM','KFMY',\
                'KRSW','KFPR','KFXE','KFLL','KGNV','KHWO','KHST','KHRT','KIMM','KINF',\
                'KVQQ','KCRG','KHEG','KJAX','KNIP','KNEN','K42J','KEYW','KNQX','KISM',\
                'KX14','KLCQ','KLAL','KX07','KLNA','KLEE','K24J','KMCF','KMTH','KMKY',\
                'KMAI','KNRB','KMLB','KCOI','KMBF','KTMB','KMIA','KOPF','KNDZ','KAPF',\
                'KTTS','KRRF','KEVB','KF45','KOCF','KOCR','KOBE','KMCO','KORL','KOMN',\
                'K28J','KXFL','KECP','KCOF','KPNS','KNPA','K40J','KFPY','K54A','KPCM',\
                'KPMP','KX41','KPGD','K2J9','KSFB','KSRQ','KX26','KSEF','KSGJ','KSPG',\
                'KPIE','KSUA','KTLH','KTPA','KTPF','KVDF','KVVG','KTIX','KPAM','KTDR',\
                'KVNC','KTRV','KVRB','KPBI','KNSE','KX60','KGIF','KZPH','KABY','KAMG',\
                'KACJ','KAHN','KFTY','KATL','KPUJ','KAGS','KDNL','KBGE','KBHC','KDZJ',\
                'KBIJ','KBQK','KSSI','K6A1','KCZL','KCXU','K18A','KCNI','KCTJ','KVPC',\
                'KCWV','K48A','KCSG','KCKF','KAJR','K9A1','KCVC','KDNN','KMGE','K17J',\
                'KDQH','KDBN','KEZM','K27A','KEBA','KFZG','KLSF','KLHW','KGVL','K49A',\
                'K3J7','K6A2','K4A7','KHMP','KAZE','KHOE','KJZP','K19A','KJCA','KJES',\
                'K9A5','KLGC','KLZU','K2J3','KMCN','KRYY','KHQU','KHME','KMHP','KMLJ',\
                'K2J5','KD73','KVAD','KMGR','KMUL','KCCO','KFFC','KPDK','KPXE','KPIM',\
                'KRVJ','KRMG','KOKZ','KSVN','KSAV','KTBR','KSBO','KJYL','KOPN','KTVI',\
                'KTMA','KTOC','KVLD','KVDI','KWRB','KIIY','KAYS','KWDR','PHBK','PHSF',\
                'PHHN','PHIK','PHTO','PHNL','PHOG','PHKO','PHJR','PHLU','PHNG','PHJH',\
                'PHNY','PHLI','PMDY','PHMO','PHMK','PHHI','KAXA','KAMW','KIKV','KAIO',\
                'KADU','KBNW','KBRL','KCIN','KCID','KTVK','KCNC','KCCY','KCKP','KICL',\
                'KCAV','KCWI','KCBF','KCSQ','KDVN','KDEH','KDNS','KDSM','KDBQ','KEST',\
                'KFFL','KFXY','KFOD','KFSW','KGGI','KHPT','KHNR','KIIB','KIOW','KIFA',\
                'KEOK','KOXV','KLWD','KLRJ','KMIW','KMCW','KSXK','KMXO','KMPZ','KMUT',\
                'KTNU','KOLZ','KORC','KI75','KOOA','KOTM','KPEA','KPRO','KRDK','KSHL',\
                'KSDA','KSUX','KSPW','KSLB','KVTI','KAWG','KALO','KEBS','KBOI','K65S',\
                'KBYI','KEUL','KLLJ','KCOE','KDIJ','KGIC','KSUN','KIDA','KJER','KLWS',\
                'KP69','KMLD','K77M','KMYL','KMUO','KMLP','KMAN','K1U7','KPIH','KRXE',\
                'KSMN','KU78','KS14','KSNT','KTWF','KSZT','KALN','KBMI','KCPS','KCIR',\
                'KMDH','KCUL','KENL','KCMI','KARR','KDPA','KMDW','KIGQ','KCGX','KORD',\
                'KDNV','KDEC','KDKB','KC73','K1H2','KFWC','KFOA','KFEP','KGBG','KGRE',\
                'KHSB','KIJX','KJOT','KIKK','KC75','KLWV','KAAA','K3LF','KMQB','KMWA',\
                'KMMO','KMTO','KM30','KMLI','KC56','KC09','KAJG','KI63','KMVN','KOLY',\
                'KPWK','KPRG','KPIA','KVYS','KPPQ','KPNT','KUIN','KTIP','KRSV','KRPJ',\
                'KRFD','KLOT','KSLO','KSFY','K06C','KBLV','KSAR','KSPI','KSQI','KTAZ',\
                'KVLA','KUGN','KAID','KANQ','KHBE','KGWB','KBMG','KBAK','KCEV','KCFJ',\
                'KDCY','KEKM','KEVV','KFWA','KSMD','KFKR','KFRH','KGYY','KGSH','K4I7',\
                'KGPC','KHFY','KGUS','K1II','KHNB','KHHG','KTYQ','KEYE','KIND','KMQJ',\
                'KJVY','KC62','KOXI','KOKK','KLAF','KPPO','KGGP','KIMS','KMZZ','KMGC',\
                'KMCX','KMIE','KC65','KPLD','KRZL','KRID','KRCR','KGEZ','KSBN','KHUF',\
                'KVPZ','KASW','KK78','KADT','K3AU','KK88','K1K1','KUKL','KCNU','KCFV',\
                'KCBK','K3K8','KCNK','KDDC','KEQA','KEHA','K9K7','KEMP','K13K','KFLV',\
                'KFSK','KFRI','KGCK','KK68','KGLD','KGBD','KGNL','K8K2','KHYS','KHD7',\
                'KHLC','KHOX','KHQG','KHQG','KHUT','KIDP','KJN8','KJHN','K2K3','K9K8',\
                'KLWC','K3K7','KLBL','KLG5','KLYO','KMHK','KMYZ','KIAB','KMPR','KP28',\
                'KAL8','KEWK','KNRN','KOEL','KOEL','KOIN','KOJC','KIXD','KOWI','KPPF',\
                'KPHG','KPTS','KPTT','KRSL','KSLN','KTQK','KK82','KSYF','K19S','K3K3',\
                'KFOE','KTOP','KTRB','KULS','KWK6','KEGT','KBEC','KAAO','KICT','KWLD',\
                'KDWU','KBRY','KSJS','KBWG','KAAS','KCVG','KDVK','KK62','KFGX','KFTK',\
                'KFFT','K27K','KGLW','KM21','KI35','KCPF','KEHR','KHOP','K6I2','KKY8',\
                'KLEX','KLOZ','KLOU','KSDF','KLMK','K2I0','K5M9','KM25','K1A6','KEKQ',\
                'KM97','KSYM','KIOB','KCEY','KJKL','KOWB','KPAH','KPBX','KRGA','KI39',\
                'KSME','KTWT','KTZV','KBYL','KIYA','KAEX','KESF','K7R3','KATP','KAUD',\
                'KBAD','KBQP','KBTR','KBXA','KLNQ','KBVE','K7R5','KCVW','KCWF','K5R8',\
                'KDRI','KEHC','KEZP','KE12','KCMB','KEIR','K3B6','KEKE','KPOE','K9F2',\
                'KBKB','K2GL','K2LS','KGAO','KGHB','KAGI','KSQE','KL38','KREG','K3L4',\
                'KAXO','KXCN','KGRY','K28K','KHDC','KXIH','KH08','KH02','KHUM','KIPN',\
                'K7R4','K3R7','K18H','KLFT','KLCH','KGBK','KMIS','KVKY','K3F3','K5LA',\
                'KMNE','KCYD','KMDJ','KIKT','KDSF','KMLU','KIER','KARA','KMSY','KNEW',\
                'KNBG','K7N0','KVSH','KHZR','KACP','KH78','KOPL','KPTN','KAQV','K4C0',\
                'K4CO','KXPY','K1L0','KAPS','KRSN','KVBS','KP92','KDNK','KSPR','KGSM',\
                'KPZZ','KDTN','KSHV','KASD','KSCF','KSRN','K7R8','KS58','KSTZ','KUXL',\
                'KTVR','K1B7','KVQT','KVNP','K0R4','KWBF','KW60','KBED','KBVY','KBOS',\
                'KCHH','KCQX','KCEF','KMQE','KFMH','KFIT','KHYA','KLWM','KGHG','KMVY',\
                'KACK','KEWB','KAQW','KOWD','KORE','KPSF','KPYM','KPVC','KNZW','KTAN',\
                'KBAF','KORH','KAPG','KADW','KNAK','KDMH','KMTN','KBWI','KCGE','KDMW',\
                'KW32','KCGS','KCBE','KESN','KFME','KJWX','KFDK','KGAI','K2G4','KHGR',\
                'KRSP','KOXB','KNHK','KRJD','KSBY','KW29','K2W6','KNUI','KLEW','KAUG',\
                'KBGR','KBHB','KNHZ','KCAR','KB21','K40B','KEPM','KFVE','KIZG','KGNR',\
                'KHUL','KMLT','KOLD','KPWM','KPQI','KRKD','KSFM','KWVL','KIWI','KADG',\
                'KAMN','KAPN','KARB','KBAX','KBTL','KSJX','KACB','KBEH','KRQB','KCAD',\
                'KCFS','KCVX','KFPK','KSLH','KCIU','KOEB','KP59','KDET','KONZ','KDTW',\
                'KYIP','KDRM','KESC','KFNT','KFKS','KFFX','KGLR','KGRR','KGOV','KSAW',\
                'KCMX','KMGN','KC04','KJYM','KBIV','KHTL','KOZW','KY70','KIMT','KIWD',\
                'KJXN','KAZO','KDUH','KLAN','KD95','KLDM','KMCD','KMBL','KISQ','KP75',\
                'KRMY','KTEW','KMNM','KIKW','KTTF','KMOP','KP53','KMKG','KERY','KOSC',\
                'KRNP','KPLN','KPTK','KP58','KPHN','KPZQ','KHYX','KMBS','KSVM','KANJ',\
                'KSSM','KMTC','KLWA','KIRS','KHAI','KTVC','KVLL','KY31','KAIT','KAEL',\
                'KAXN','KAQP','KAUM','KBDE','KBJI','KBBB','KFOZ','KBRD','KCFE','KCBG',\
                'KRYM','K27D','KCNB','KCOQ','KCQM','KCDD','KCKN','KDTL','KTOB','KDLH',\
                'KDYT','KY63','KELO','KEVM','KFRM','KFBL','KFFM','KFGN','KFSE','KGYL',\
                'KGHW','KCKC','KGNA','KGRM','KGPZ','KGDB','KHCO','KHIB','K04W','KHCD',\
                'KINL','KMJQ','K21D','KLJF','KLXL','K14Y','KXVG','KLYV','KDXX','K3N8',\
                'KMKT','KMGG','KMML','KHZX','KANE','KMSP','KLVN','KMIC','KFCM','KMVE',\
                'KJKJ','KMZH','KJMR','KMOX','KULM','KOVL','KORB','KVVV','KOWA','KPKD',\
                'KPEX','KPWC','KPQN','KFKA','KPNM','KRGK','KRWF','KRST','KROX','KROS',\
                'KD39','KBFW','KDVP','KSGS','KSYN','KSAZ','KSTC','KJYG','K9MN','KSTP',\
                'KTVF','KP61','KTKC','KTWM','KADC','KY49','KRRT','KACQ','KVWU','KETH',\
                'KBDH','KILL','KMWM','KONA','KOTG','KVER','KBBG','KFWB','KH21','KOZS',\
                'KEZZ','KCGI','KCDJ','KGLY','KCOU','KFAM','KTBN','KGVW','KHAE','KLRY',\
                'KJEF','KJLN','KAIZ','KMKC','KMCI','KTKX','KIRK','KLBO','KLXT','KMAW',\
                'KMHL','KEVU','KMYJ','KMBY','KHFJ','KGPH','KEOS','KNVD','KK02','KPCD',\
                'KPYN','KPOF','KDMO','KSIK','KP35','KSGF','KSET','KSTJ','KSTL','KSUS',\
                'KUUV','KVIH','KRCM','KRAW','KFYG','KUNO','KSZL','KM40','KHSA','K01M',\
                'KBIX','K1R7','KCKM','KRNV','K0R0','KCBM','KCRX','KGTR','KGLH','KGWO',\
                'KGNF','KGPT','KHBG','KIDL','KMYT','KHKS','KJAN','KLUL','KMBO','KMCB',\
                'KMEI','KNMM','KNJW','KHEZ','KOLV','KUOX','KPMU','KPGL','KPQL','KMJD',\
                'KPIB','KJVW','KSTF','KUTA','KTUP','KVKS','KDLP','K5A6','K1AM','K3U3',\
                'KBHK','K6S0','KBIL','KBZN','K1BM','K8S0','KBTM','K1CM','KS71','KCII',\
                'K4U6','KM46','KS85','KCTB','K38S','K1DM','KDLN','K3DU','K1EM','K97M',\
                'KEKS','K88M','K1S3','K79S','K1FM','KGGW','KGDV','K1GM','KGTF','K6S5',\
                'KHRF','K00U','K3HT','KHVR','KHLN','K1HM','K1IM','KJDN','K1JM','KGPI',\
                'K1KM','K6S8','KLWT','KS59','K1LM','KLVM','KGFA','KM75','K1MM','KMLS',\
                'KMSO','KMVH','K1NM','K1OM','KS34','KPWD','KPO1','K7S0','KRPX','K9S2',\
                'KSDY','K3TH','KTHM','K9S5','K7S1','KRVF','KWEY','KWYS','K7S6','KOLF',\
                'KASJ','KVUJ','KRHP','KHBI','KAVL','KMRH','KNJM','KTNB','KBUY','KHAT',\
                'KIGX','KCLT','KNKT','KCTZ','KJQF','KONX','KEXX','KEDE','KECG','KEYF',\
                'K7W6','KHRJ','KFAY','KFBG','KAKH','KGSB','KGWW','KGSO','KIXA','KHSE',\
                'KHNZ','KHKY','KHFF','KOAJ','KGEV','KDPL','KFFA','KISO','KIPJ','KLHZ',\
                'KLBT','K1A5','KMQI','KMEB','KEQY','KMRN','KMWK','KEWN','KNCA','KNBT',\
                'KPGV','KPOB','KRDU','KSIF','KRZZ','KRCZ','KRWI','KTDF','KFQD','KRUQ',\
                'KTTA','KEHO','K5W8','KSCR','KJNX','KSOP','KSUT','KSVH','K2DP','K24A',\
                'KETC','KAFP','KOCW','KCPC','KUKF','KILM','KINT','K20U','KBIS','KBPP',\
                'KBWW','K9D7','K46D','K2C8','KS32','KD50','KDVL','KP11','KDIK','KFAR',\
                'KN60','KD57','KGAF','KRDR','KGFK','KGWR','K5H4','KHZE','KHEI','KJMS',\
                'KD55','KP67','K7L2','KY19','KMIB','KMOT','K2D5','K06D','KRUG','K08D',\
                'KD60','KBAC','KBWP','K96D','KS25','KXWA','KISN','KANW','KBVN','KAIA',\
                'KAUH','KBIE','K42V','KBTA','K1BW','KBBW','KCDR','KCHM','K1CW','KOLU',\
                'K1DW','K1EW','KFNB','K1FW','KFET','K1GW','KGRN','KGRI','KHSI','KHJH',\
                'KHDE','K1HW','KIML','K1IW','KEAR','K1KW','KIBM','KLXN','KLNK','KMCK',\
                'KAFK','KOFK','KOVN','KLBF','KOFF','KOGA','KOMA','KMLE','KONL','KODX',\
                'KPMV','KBFF','KSNY','KTQE','KTIF','KVTN','KAHQ','KLCG','KJYR','KBML',\
                'KCON','KAFN','KEEN','KLCI','KLEB','KMHT','KMWN','KASH','K1P1','KPSM',\
                'KDAW','KHIE','KN85','K12N','KACY','KBLM','K1N7','KCDW','K17N','KN81',\
                'KNEL','KN12','KN07','KLDJ','KN14','K47N','KMIV','KMMU','KVAY','KEWR',\
                'K26N','K3N6','KN40','K39N','KN87','KSMQ','KFWN','KTEB','KMJX','KTTN',\
                'K4N1','KWWD','KOBI','KWRI','KALM','KABQ','KAXX','KATS','KBRG','KE80',\
                'KCVS','KCNM','KE33','KCAO','KCQC','KCVN','K4CR','KDMN','KAEG','KFMN',\
                'KGUP','KGNT','KHBB','KHOB','KHMN','KLRU','KLVS','KLSB','KLAM','KM63',\
                'K4MR','K0E0','K4MY','KRTN','KROW','KSAF','KSXU','K5T6','KDNA','KSRR',\
                'KSVC','KONM','K0A0','KSKX','K4SL','KTCS','KTCC','K2C2','KTMT','KU31',\
                'KB23','KBVU','KCXP','KDRA','KEKO','KELY','K05U','KP68','KNFL','KINS',\
                'KL63','KLAS','KLSV','KLOL','KMEV','KVGT','KRNO','KRTS','KTPH','KBJN',\
                'KHND','K9BB','KAWH','KWMC','KALB','KGVQ','KBGM','KHWV','KBUF','KD38',\
                'KIUA','KN03','KDSV','KDKK','KHTO','KELM','KCZG','KFRG','KGTB','KFZY',\
                'KGFL','KVGC','K4G6','K1B1','KISP','KITH','KJHW','KNY0','KJRB','KMSS',\
                'KMTP','KMGJ','KMSV','KSWF','KIAG','KOIC','KNYC','KJFK','KLGA','KOGS',\
                'KOLE','KPEO','KPBG','KPLB','KPTD','KPOU','KROC','KRME','KSLK','K5B2',\
                'KSCH','KN23','K6B9','KSYR','KUCA','KART','KELZ','KFOK','KHPN','KSDC',\
                'KAKR','KCAK','KHZY','KUNI','KI69','KEDJ','KCDI','KRZT','KLUK','KCYO',\
                'KBKL','KCLE','KCGF','KTZR','KCMH','KOSU','KDAY','KMGY','KDFI','KDLZ',\
                'KFDY','KFBC','KHAO','KI67','KI43','KLHQ','KI68','KAOH','KUYF','KLPR',\
                'KMFD','KMNN','KMRT','KMWO','K4I3','KVTA','KPHD','KOWX','KOXD','KPCW',\
                'KPMH','KPOV','KLCK','KSGH','KTDZ','KTOL','KI74','KVNW','KVES','KAXV',\
                'KI23','KUSE','KLNN','KILN','KBJJ','KFFO','KI19','KYNG','KZZV','KADH',\
                'KLTS','KAXS','KAVK','K1F0','KADM','KAQR','KBVO','KBKN','KCQB','KCHK',\
                'KGCM','KCLK','KCSM','KCUH','KDUC','KDUA','KELK','KRQO','KEND','KWDG',\
                'KFSI','KFDR','KGAG','KGMJ','KGOK','KGUY','KHBR','KHHW','K4O4','KLAW',\
                'KHMY','KMLC','KMIO','KMKO','KOUN','KRCE','KHSD','KPWA','KOKC','KOKM',\
                'KPVJ','KPNC','KRKR','KH71','KJSV','KOWP','KSRE','KSNL','KGZL','KSWO',\
                'KTQH','KTIK','KRVS','KTUL','KJWG','KOJA','KWWR','KAST','KUAO','KBKE',\
                'KBDN','KBOK','KBNO','K92S','KCZK','K3CL','KCVO','K77S','KEUG','K6S2',\
                'K4S1','K3S8','KHRI','KHIO','K4S2','KJSY','KGCD','KLMT','KLGD','KLKV',\
                'KS33','KMMV','KMEH','KMFR','KJNW','KONP','KOTH','KONO','KPDT','KPDX',\
                'KS39','KRDM','KP88','KREO','KRRK','KRBG','KSLE','KSPB','K2SL','KSXT',\
                'KS21','KDLS','KTMK','KTTD','KABE','KXLL','KAOO','KAVP','KBVI','KHMZ',\
                'KBFD','KBTP','KFIG','KMQS','KVVS','KDYL','KDUJ','KERI','KRYT','KFKL',\
                'K29D','KCXY','KHZL','KIDI','KJST','KLNS','KLBE','K22N','KLHV','KGKJ',\
                'KMDT','KMPO','KMUI','KUCP','KCKZ','KPHL','KPNE','KPSB','KLOM','KAGC',\
                'KPIT','KPTW','KUKT','KRDG','KRVL','KSEG','K2G9','KUNV','KOYM','KN27',\
                'KAFJ','KN38','KOQN','KIPT','KTHV','KPJC','KBID','KUUU','KOQU','KSFZ',\
                'KPVD','KWST','KAIK','KAQX','KAND','KBNL','KARW','KNBC','KMKS','KCDN',\
                'KJZI','KCHS','KCQW','KDCM','KCEU','KCAE','KCUB','KHYW','KUDG','KFLO',\
                'KGGE','KGMU','KGYH','KGRD','KGSP','KHVS','KHXD','KCKI','KLKR','KLUX',\
                'KMNI','KMAO','KBBP','KMMT','KLRO','KMYR','KEOE','KXNO','KCRE','KOGB',\
                'KLQK','KUZA','KSSC','KSPA','KDYB','KSMS','K35A','KRBW','KFDW','KABR',\
                'KADR','KBAT','KBEL','KEFC','KBVD','K6V5','KBRA','KBTN','KBKX','K2WX',\
                'KCAC','K9V9','K8D7','KCUT','K6E5','K84D','KED0','KRCA','KEL0','KD07',\
                'K3FU','KFED','K0D8','KGLV','K9D1','KHRD','KHER','KHSR','KHON','KPAC',\
                'KKAD','KY22','KLEM','KMDS','K9V6','K1D1','KMKA','KMHE','KMBG','K98D',\
                'K8V3','KPHP','KPIR','KIEN','K1D3','KRAP','KUNR','KREL','KNE0','KSL0',\
                'KFSD','K8D3','KSPF','K49B','KSUM','KY14','KTLS','KVMR','KVIC','KVIV',\
                'KAGZ','K6V4','KWTA','KATY','K1D7','K4X4','KICR','KYKN','KMMI','KM08',\
                'KTRI','KCHA','KCKV','KRZR','K3M3','KMRC','KM04','KCSV','K2A0','KM01',\
                'KM02','KDYR','K0A9','KFYM','KM52','KM33','KXNX','KGKT','KGCY','KHZD',\
                'KJAU','KMKL','KDKX','KTYS','K2M2','KM54','KLUG','KPVE','K8A3','KMNV',\
                'KRNC','KMEM','KNQA','K2M8','KMOR','KMBT','KBNA','KJWN','KOQT','KSCX',\
                'KPHT','K1M5','KGZS','KRKW','KSNH','KSYI','KMQY','KFYE','KSRB','KM91',\
                'KTHA','KUCY','KBGF','KABI','KGYF','KHHV','KALI','KE38','KAMA','KE11',\
                'KLBX','KGKY','KF44','KEDC','KAUS','KATT','KBYY','KBMT','KBPT','KBEA',\
                'KE41','KBPG','KF00','KBGD','K0F2','KBBD','KBBF','KBQX','KBKD','K11R',\
                'KXBP','KBRO','KBWD','KCFD','KBMQ','KRWV','KT35','KHHF','KCZT','K4F2',\
                'KCVB','KNGP','KF17','KCDS','KGZN','KLBR','KCPT','K6R3','KCOM','KCLL',\
                'K66R','KMKN','KCXO','KCRP','KCRS','KCOT','KDKR','KDHT','KADS','KDFW',\
                'KDAL','KNBE','KRBD','KLUD','KDRT','KDTO','KFTN','K6R6','KDUX','KDYS',\
                'KELA','KETN','KEMK','KVAF','KEBG','KELP','KBKS','KBIF','KFST','KFWS',\
                'KFTW','KNFW','KT82','KHLR','KAFW','KGLE','KGVX','KGLS','KGOP','KGTU',\
                'KGYB','KJXI','KT20','KRPH','KGDJ','KGPM','KGRK','KGVT','KGDP','KGUL',\
                'KMNZ','KHRL','KLHB','KHBV','KRFI','KHRX','KINJ','KHQI','KHDO','KDZB',\
                'KDWH','KEFD','KTME','KHOU','KIAH','KLVJ','KAXH','KSGR','KMCJ','KUTS',\
                'KTFP','KJSO','KJAS','KJCT','KSKF','K2R9','KERV','KCWC','KILE','KIKG',\
                'KNQI','KRYW','K3T5','K2F5','KLUV','KLZZ','KLNC','KT41','KLRD','KT70',\
                'KDLF','KLLN','KT78','KAQO','KGGG','KLBB','KLFK','KMRF','KASL','K5T9',\
                'KMFE','KPWG','KTKI','KNMT','KHQZ','KLXY','KMDD','KMAF','KJWY','KJDD',\
                'KMWL','KOSA','KMZG','KMIU','KOCH','KBAZ','KOPM','KODO','KNOG','KORG',\
                'KOZA','KPSX','KPSN','KPPA','KBPC','KPRX','KPEQ','KPYX','K25T','KPVW',\
                'KPEZ','KRAS','KPIL','KPKV','KPRS','KT77','KRND','K6P9','KREE','KRBO',\
                'KRKP','KECU','KF46','KRPE','KSJT','KSAT','KP07','KHYI','KT98','K81R',\
                'K5C1','KSSF','KSEQ','KGNC','KGYI','KT69','KSNK','KSOA','KSPL','KE42',\
                'KSEP','KSLR','KSWW','KT74','KTPL','KTRL','KTYR','KUVA','KVHN','KF05',\
                'KVCT','KACT','KCNW','KJSL','KCRH','KT65','KTXW','KIWS','KARM','KSPS',\
                'KINK','KAPY','KU52','K4BL','KBDG','KBMC','KBCE','KCDC','KDTA','KU24',\
                'KU69','KDPG','KU16','KU28','K4HV','KHVE','K36U','KHCR','KHIF','KKNB',\
                'KLGU','K41U','KMLF','KCNY','KOGD','KU55','KPUC','KPVU','K74V','KU67',\
                'KDXZ','KSGU','KSLC','KU42','KSPK','KT62','KTVY','KVEL','KENV','KVJI',\
                'KBCB','KBKT','KVBW','K0V4','K7W4','KCHO','KCXE','KCPK','KW63','KW81',\
                'KCJR','KDAN','KPSK','KEMV','KFVX','KNFE','KDAA','KFKN','KEZF','KFRR',\
                'KFAF','KGVE','KHLX','KHSP','K0VG','KW31','KLFI','KLVL','KJYO','KLKU',\
                'KLUA','KLYH','KHEF','KMKJ','KMTV','KMFV','K8W2','KPHF','KPVG','KORF',\
                'KNGU','KAKQ','KNTU','KOMH','KPTB','KNYG','KW96','KJFZ','KFCI','KOFP',\
                'KRIC','KROA','KW75','KW78','KAVC','KRMN','KSHD','KSFQ','KTGI','KXSA',\
                'KWAL','KHWY','KIAD','KW13','KFYJ','KJGG','KOKV','KLNP','KDDH','KBTV',\
                'KFSO','KCDA','K6B0','KMPV','KMVL','KEFK','KRUT','KVSF','K1V4','KAWO',\
                'KBLI','KPWT','KBVS','KCLS','KCQV','KDEW','KORS','KELN','KEPH','KPAE',\
                'KSKA','KGRF','KFHR','KHMS','KHQM','KKLS','KS52','KMWH','KOKH','KOLM',\
                'KOMK','KPSC','KNOW','KCLM','K0S9','KPUW','KPLU','KUIL','KRNT','KRLD',\
                'KBFI','KSEA','KSHN','KSFF','KGEG','KSMP','K1S5','KTIW','KTCM','KTDO',\
                'KVUO','KALW','KEAT','KNUW','K1YT','KYKM','K1QW','KAIG','KATW','KASX',\
                'KGRB','KBCK','KOVS','KBUU','KY23','KCLI','KUBE','KDLL','KEGV','K57C',\
                'KEAU','K3D2','KFLD','KHYR','KJVL','KUNU','KENW','KLSE','KRCX','KLNL',\
                'K4R5','KLNR','KMSN','KMTW','KD25','KMFI','K82C','KMDZ','KLUM','KRRL',\
                'KC29','KMKE','KMWC','KMRJ','KARV','KEFT','KCWA','KRNH','KOCQ','KOEO',\
                'KOSH','KPBH','KPVB','KPDC','KRAC','KC35','KRHI','KRPD','KEZS','KSBM',\
                'KRZN','KOLG','KCMY','KSTE','KSUE','KSUW','KTKV','KY51','KVOK','K2P2',\
                'KRYV','KUES','KPCZ','KAUW','KY50','KETB','KISW','KBKW','KBLF','KW22',\
                'KCRW','KCKB','KEKN','KHTS','KLWB','K6L4','KMRB','KMGW','KPKB','KW99',\
                'KI16','K3I2','K48I','KHLG','KSSU','KTMH','KAFO','K1AW','K46U','KARL',\
                'KBVR','KBFU','KBPI','KBIT','KBRX','KTBX','KBYG','KCPR','KCMS','KCYS',\
                'KCHJ','KCOD','KCTD','KU68','KDHS','KDRC','KDWX','KDGW','KDUB','KEHY',\
                'KEVW','KFIR','KFBR','KGCC','KGEY','KGUR','KGUN','KHLD','KW43','KIDV',\
                'KIKA','KJAC','KEMM','KLND','KLAR','KAJL','KLSK','KMMM','KMTR','KECS',\
                'KPAT','K82V','KPNA','KPIN','KPOY','KPUM','KRWL','KRIM','KRIW','KRKS',\
                'KSGE','KSAA','KSHR','KSHC','KSIB','KSKL','KFWZ','KJPD','KHSG','KTOR',\
                'KTOW','KVDW','KFEW','KEAN','KWTR','KWRL','KP60','KDCA']
               }
